# Generated by Django 4.2.6 on 2023-10-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=64)),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
