# Generated by Django 4.2.7 on 2023-11-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_employee_is_admin_alter_admin_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
