# Generated by Django 4.2.7 on 2023-11-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_employee_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='available_pto',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='available_sickdays',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
