# Generated by Django 4.2.7 on 2023-11-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_admin_is_admin_alter_employee_available_pto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(default='user first name', max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(default='user last name', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='user first name', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='user last name', max_length=64),
        ),
    ]
