# Generated by Django 4.2.6 on 2023-12-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_employee_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('Vice President', 'Vice President'), ('Software Engineer', 'Software Engineer'), ('System Administrator', 'System Administrator'), ('QA Engineer', 'QA Engineer'), ('Director', 'Director'), ('Manager', 'Manager'), ('Administrator', 'Administrator'), ('HR Administrator', 'HR Administrator'), ('Intern', 'Intern')], max_length=30),
        ),
    ]
