# Generated by Django 4.2.7 on 2023-11-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_admin_first_name_alter_admin_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_admin',
        ),
    ]
