# Generated by Django 4.2.6 on 2023-11-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence_Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
                ('absent_counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication_Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
                ('count_publications', models.IntegerField(default=0)),
            ],
        ),
    ]
