# Generated by Django 4.2.6 on 2023-11-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence_calendar',
            old_name='absent_date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='absence_calendar',
            old_name='absent_date_start',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='publication_calendar',
            name='count_publications',
            field=models.IntegerField(default=0),
        ),
    ]
