# Generated by Django 4.2.6 on 2023-11-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_leave', '0003_alter_request_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('PTO', 'Paid Time Off'), ('Sick Day', 'Sick Day')], max_length=8),
        ),
    ]
