# Generated by Django 4.2.6 on 2023-11-17 18:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('body_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('publication_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
