# Generated by Django 4.2.6 on 2023-11-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('body_description', models.TextField()),
                ('image_address', models.CharField(max_length=256)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
