# Generated by Django 4.2.6 on 2023-11-03 20:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='body_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
