# Generated by Django 4.2.6 on 2023-11-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_publication_body_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image_address',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
