# Generated by Django 4.2.6 on 2023-11-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_remove_publication_image_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
