# Generated by Django 4.2.6 on 2023-11-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_alter_publication_publication_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-publication_date']},
        ),
    ]
